name: CD - GitHub Docker Packages & Deploy Render
on:
  push:
    branches: [master]
env:
  REGISTRY: ghcr.io # GitHub Container Registry (GHCR)
  REPOSITORY: ${{ github.repository }}
  AWS_ECR_URL: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/miw-upm
jobs:
  cd:
    name: Build & Push GitHub Package & Deploy on Render Docker Image
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 21
      - name: Get version from pom.xml
        id: get-version
        run: |
          echo "VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
          echo "ARTIFACT=$(mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout)" >> $GITHUB_ENV
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }} # GitHub Container Registry (GHCR)
          username: ${{ github.actor }}
          # 1º Creación del Token de Acceso Personal
          #    Cuenta de GitHub >> Developer settings >> Personal access tokens >> Tokens >> Generate new token
          #    write:packages & read:packages & delete:packages & repo
          # 2º Configuración de Secrets en GitHub
          #    repositorio en GitHub >> settings >> secrets and variables >> actions >> new repository secret
          password: ${{ secrets.GHCR_PERSONAL_ACCESS_TOKEN }}
      - name: Build Docker image
        run: docker build  -t $REPOSITORY:$VERSION .
      - name: Tag and Push on GitHub Packages
        run: |
          docker tag $REPOSITORY:$VERSION $REGISTRY/$REPOSITORY:$VERSION
          docker tag $REPOSITORY:$VERSION $REGISTRY/$REPOSITORY:latest
          docker push $REGISTRY/$REPOSITORY:$VERSION
          docker push $REGISTRY/$REPOSITORY:latest
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Iniciar sesión en AWS ECR
        uses: aws-actions/amazon-ecr-login@v2
      - name: Verificar valores de variables
        run: |
          echo "$AWS_ECR_URL"
          echo "$ARTIFACT:latest"
          echo $AWS_ECR_URL/$ARTIFACT:latest

      - name: Tag and Push AWS ECR
        run: |
          docker tag $REPOSITORY:$VERSION $AWS_ECR_URL:latest
          docker push $AWS_ECR_URL:latest
